# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         List-Util-Superpositions
version:      1.1
version_from: lib/List/Util/Superpositions.pm
installdirs:  site
requires:
    List::Util:                    0
    Quantum::Superpositions:       0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
